---

require:
  - rubocop-minitest
  - rubocop-rake

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Exclude:
    - examples/**/*.rb

Lint/SuppressedException:
  Exclude:
    - test/helpers/circuit_breaker_helper.rb
    - test/adapters/net_http_test.rb
    - test/protected_resource_test.rb
    - examples/**/*.rb

Minitest/RefuteFalse:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/semian/extconf.rb

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
