---

version: "3.7"
services:
  semian: &base
    container_name: semian
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
      target: base
    working_dir: /workspace
    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace
    # Required for ptrace-based debuggers like C++, Go, and Rust
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      - redis
      - mysql
      - toxiproxy
    command:
      - /bin/bash
      - -c
      - |
          bundle install
          sleep infinity

  test:
    <<: *base
    container_name: semian-tests
    hostname: http-server  # this is important because it's also serving as an http server
    build:
      context: ../
      dockerfile: dockerfiles/semian-ci
    command:
      - bash
      - -c
      - |-
          if [ -f .env ]; then
            set -a
            source .env
            set +a
          fi
          ./scripts/run_tests.sh ${DEBUG:+--with-debugger}
    ports:
      - 12345:12345  # Debugger port
    profiles:
      - test

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    container_name: toxiproxy
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server

  mysql:
    container_name: mysql
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
