---

    name: Release
    
    on:
      workflow_dispatch:
        inputs:
          release_type:
            description: "Type of release"
            required: true
            type: choice
            options:
              - major
              - minor
              - patch
    
    jobs:
      test:
        name: Run tests
        uses: ./.github/workflows/test.yml
    
      read-version:
        name: Read current version and calculate new version
        runs-on: ubuntu-latest
        outputs:
          current_version: ${{ steps.current_version.outputs.version }}
          new_version: ${{ steps.new_version.outputs.version }}
        steps:
          -
            name: Checkout
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
          -
            name: Set up Ruby
            uses: ruby/setup-ruby@v1.263.0
            with:
              ruby-version: "3.4"
              bundler-cache: true
          -
            name: Read current version
            id: current_version
            run: |
              current_version=$(ruby -e "require './lib/semian/version'; puts Semian::VERSION")
              echo "version=$current_version" >> $GITHUB_OUTPUT
              echo "Current version: $current_version"
          -
            name: Calculate new version
            id: new_version
            run: |
              chmod +x .github/scripts/calculate_version.sh
              .github/scripts/calculate_version.sh \
                "${{ steps.current_version.outputs.version }}" \
                "${{ github.event.inputs.release_type }}"
      
      update-version:
        name: Update version file and create tag
        runs-on: ubuntu-latest
        needs: [test, read-version]
        permissions:
          contents: write
        env:
          BUNDLE_FROZEN: false
        steps:
          -
            name: Checkout
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
            with:
              fetch-depth: 30
              fetch-tags: true
          -
            name: Set up Ruby
            uses: ruby/setup-ruby@v1.263.0
            with:
              ruby-version: "3.4"
              bundler-cache: true
          -
            name: Update version file
            run: |
              new_version="${{ needs.read-version.outputs.new_version }}"
              sed -i "s/VERSION = \".*\"/VERSION = \"$new_version\"/" lib/semian/version.rb
              echo "Updated version file:"
              cat lib/semian/version.rb
          -
            name: Update Gemfile.lock
            run: |
              # Update Gemfile.lock with new version
              bundle install
          -
            name: Update CHANGELOG
            run: |
              chmod +x .github/scripts/update_changelog.sh
              .github/scripts/update_changelog.sh \
                "${{ needs.read-version.outputs.new_version }}" \
                "${{ needs.read-version.outputs.current_version }}"
          -
            name: Commit and tag version
            run: |
              new_version="${{ needs.read-version.outputs.new_version }}"
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add lib/semian/version.rb Gemfile.lock CHANGELOG.md
              git commit -m "Bump version to $new_version" -m "Triggered by @${{ github.actor }}"
              git tag "v$new_version"
              git push origin main
              git push origin "v$new_version"
    
      build-and-release:
        name: Build gem and create GitHub release
        runs-on: ubuntu-latest
        needs: [update-version, read-version]
        permissions:
          contents: write
        steps:
          -
            name: Checkout
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
            with:
              # Uses main branch to get the updated version after the commit
              ref: main
          -
            name: Set up Ruby
            uses: ruby/setup-ruby@v1.263.0
            with:
              ruby-version: "3.4"
              bundler-cache: true
          -
            name: Build C extension
            run: bundle exec rake build
          -
            name: Build gem
            run: |
              gem build semian.gemspec
          -
            name: Generate SHA512 checksum
            run: |
              for gem in semian-*.gem; do
                sha512sum "$gem" > "${gem}.sha512"
              done
          -
            name: Draft GitHub release
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              tag="v${{ needs.read-version.outputs.new_version }}"
              gh release create "$tag" \
                --title "$tag" \
                --generate-notes \
                --draft \
                semian-*.gem \
                semian-*.gem.sha512
          -
            name: Filter dependabot commits
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              tag="v${{ needs.read-version.outputs.new_version }}"
              gh release view "$tag" --json body -q '.body' > temp_notes.md
              grep -v -i "bump.*by.*dependabot" temp_notes.md > filtered_notes.md || true
          -
            name: Publish release
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              tag="v${{ needs.read-version.outputs.new_version }}"
              gh release edit "$tag" \
                --notes-file filtered_notes.md \
                --draft=false
    
    